### ISSUE TITLE
[BUG] IndexError: list index out of range

### ISSUE THREAD

**Issue by FuckingToasters** [Vinyzu/Botright#1]
**Describe the bug**
It can't index the list and save the content in the image_url variable

**Code Sample**
```py
 Error:
 Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\DISLOCK V2\main.py", line 109, in generate_unclaimed
    await self.page.solve_hcaptcha()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\botright\modules\playwright_mock\page.py", line 334, in solve_mocker
    return await hcaptcha.hCaptcha.solve_hcaptcha(page, rqdata=rqdata)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\botright\modules\hcaptcha.py", line 189, in solve_hcaptcha
    return await hCaptcha.solve_captcha(page, checkbox)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\botright\modules\hcaptcha.py", line 102, in solve_captcha
    image_url = style.split('url("')[1].split('"')[0]
IndexError: list index out of range
```

**To Reproduce**
1. Run the main.py file
2. Wait until Browser is spawned
3. Notice the error i sent above
4. This error happen in the botright liebary so i'm asking here

**Expected behavior**
Code should work i guess :)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by Vinyzu** [comment]
Can you please provide your code?
Can you reproduce this error everytime?

**Comment by FuckingToasters** [comment]
> Can you please provide your code? Can you reproduce this error everytime?

Yes, it happen every time when using V2 with botright implementation and i don't know from what i should provide code, i have nothing changed in botright/modules/hcaptcha.py

**Comment by Vinyzu** [comment]
Your code please

**Comment by Vinyzu** [comment]
Fixed: https://github.com/Vinyzu/Botright/commit/895d2adab4725b0ee232542899ef0607840d742b
