### ISSUE TITLE
[BUG] Can't import Botright

### ISSUE THREAD

**Issue by Impre-visible** [Vinyzu/Botright#12]
**Describe the bug**
Hi, I can't import Botright.

**Code Sample**
```
Traceback (most recent call last):
  File "g:\Projets\XXXXXXXXXXXXXXX\main.py", line 9, in <module>
    import botright
  File "C:\Users\imprv\AppData\Local\Programs\Python\Python310\lib\site-packages\botright\__init__.py", line 1, in <module>
    from .botright import *
  File "C:\Users\imprv\AppData\Local\Programs\Python\Python310\lib\site-packages\botright\botright.py", line 6, in <module>
    from .modules.playwright_mock import browser
  File "C:\Users\imprv\AppData\Local\Programs\Python\Python310\lib\site-packages\botright\modules\playwright_mock\__init__.py", line 7, in <module>
    from .page import new_page
  File "C:\Users\imprv\AppData\Local\Programs\Python\Python310\lib\site-packages\botright\modules\playwright_mock\page.py", line 6, in <module>
    from .. import geetest, hcaptcha, recaptcha
  File "C:\Users\imprv\AppData\Local\Programs\Python\Python310\lib\site-packages\botright\modules\hcaptcha.py", line 16, in <module>
    class hCaptcha:
  File "C:\Users\imprv\AppData\Local\Programs\Python\Python310\lib\site-packages\botright\modules\hcaptcha.py", line 18, in hCaptcha
    solver.install()
AttributeError: module 'hcaptcha_challenger' has no attribute 'install
```

**To Reproduce**
1. Import botright

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Vinyzu** [comment]
Ill look into it.

**Comment by BlueSchnabeltier** [comment]
> **Describe the bug** Hi, I can't import Botright.
> 
> **Code Sample**
> 
> ```
> Traceback (most recent call last):
>   File "g:\Projets\XXXXXXXXXXXXXXX\main.py", line 9, in <module>
>     import botright
>   File "C:\Users\imprv\AppData\Local\Programs\Python\Python310\lib\site-packages\botright\__init__.py", line 1, in <module>
>     from .botright import *
>   File "C:\Users\imprv\AppData\Local\Programs\Python\Python310\lib\site-packages\botright\botright.py", line 6, in <module>
>     from .modules.playwright_mock import browser
>   File "C:\Users\imprv\AppData\Local\Programs\Python\Python310\lib\site-packages\botright\modules\playwright_mock\__init__.py", line 7, in <module>
>     from .page import new_page
>   File "C:\Users\imprv\AppData\Local\Programs\Python\Python310\lib\site-packages\botright\modules\playwright_mock\page.py", line 6, in <module>
>     from .. import geetest, hcaptcha, recaptcha
>   File "C:\Users\imprv\AppData\Local\Programs\Python\Python310\lib\site-packages\botright\modules\hcaptcha.py", line 16, in <module>
>     class hCaptcha:
>   File "C:\Users\imprv\AppData\Local\Programs\Python\Python310\lib\site-packages\botright\modules\hcaptcha.py", line 18, in hCaptcha
>     solver.install()
> AttributeError: module 'hcaptcha_challenger' has no attribute 'install
> ```
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Import botright
> 
> **Desktop (please complete the following information):**
> 
> * OS: Windows
> * Version: 10

Python and Botright version?
