### ISSUE TITLE
[BUG] Solving Captcha - RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by FuckingToasters** [Vinyzu/Botright#16]
**Describe the bug**
After the browser open and click the captcha checkbox so that the images appear, it stop do anything and after a while it close the browser along with some tracebacks.

**Code Sample**
```py
import asyncio
import botright

async def main():
    botright_client = await botright.Botright(headless=False)
    browser = await botright_client.new_browser()
    page = await browser.new_page()

    tkn = await browser.get_hcaptcha()
    print("tkn: ", tkn)
    page.goto("http://discord.com/")
    page.screenshot(path="example.png")

    await botright_client.close()

if __name__ == "__main__":
    asyncio.run(main())
```

**To Reproduce**
1. create a new main.py file with the sample code above
2. install latest botright version
3. run main.py file

**Expected behavior**

**Screenshots**
https://i.imgur.com/aQBPSap.png

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
```
C:\Users\admin\Downloads\testpy\captcha>python main.py
C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\botright\modules\hcaptcha.py", line 134, in solve_captcha
    style = await sub_element.get_attribute("style")
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\async_api\_generated.py", line 14363, in get_attribute
    await self._impl_obj.get_attribute(name=name, timeout=timeout)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\_impl\_locator.py", line 337, in get_attribute
    return await self._frame.get_attribute(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\_impl\_frame.py", line 613, in get_attribute
    return await self._channel.send("getAttribute", locals_to_params(locals()))
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\_impl\_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\_impl\_connection.py", line 396, in wrap_api_call
    return await cb()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\_impl\_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
  waiting for frame "xpath=//iframe[contains(@title,'content')] >> nth=0"
  selector resolved to visible <iframe scrolling="no" frameborder="0" title="Main conte…></iframe>
waiting for selector "//iframe[contains(@title,'content')] >> nth=0 >> internal:control=enter-frame >> //div[@class='task-image'] >> nth=0 >> [class="image-wrapper"] >> [class="image"]"
============================================================

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\Downloads\testpy\captcha\main.py", line 18, in <module>
    asyncio.run(main())
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\admin\Downloads\testpy\captcha\main.py", line 10, in main
    tkn = await browser.get_hcaptcha()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\botright\modules\playwright_mock\browser.py", line 16, in get_hcaptcha_mocker
    return await hcaptcha.hCaptcha.get_hcaptcha(browser, sitekey=sitekey, rqdata=rqdata)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\botright\modules\hcaptcha.py", line 215, in get_hcaptcha
    return await page.solve_hcaptcha(rqdata=rqdata)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\botright\modules\playwright_mock\page.py", line 343, in hcap_solve_mocker
    return await hcaptcha.hCaptcha.solve_hcaptcha(page, rqdata=rqdata)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\botright\modules\hcaptcha.py", line 210, in solve_hcaptcha
    return await hCaptcha.solve_captcha(page, checkbox)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\botright\modules\hcaptcha.py", line 137, in solve_captcha
    raise TimeoutError("Captcha Images didnt load")
TimeoutError: Captcha Images didnt load
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x00000251A74A98B0>
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\asyncio\base_subprocess.py", line 126, in __del__
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\asyncio\base_subprocess.py", line 104, in close
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000251A74D61F0>
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000251A74D61F0>
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000251A74D61F0>
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000251A74D61F0>
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
```

**Comment by Vinyzu** [comment]
You missed two await statements:
```py
await page.goto("http://discord.com/")
await page.screenshot(path="example.png")
```
also Fixed with update [v0.4](https://github.com/Vinyzu/Botright/commit/d8a00b5b6ed596bf3067437bbf2e01cbfad4c00b)
