### ISSUE TITLE
[BUG] IndexError: list index out of range on captcha solving

### ISSUE THREAD

**Issue by FeelsBadMan1** [Vinyzu/Botright#4]
**Describe the bug**
hcaptcha solving raise a keyerror
issue is being raised in `botright\modules\hcaptcha.py` on line 102
i haven't changed any code in the botright folder but changed a few things in the discordgenerator file (not changed anything which has to do with captcha solving tho)

**Code Sample**
```py
 Error:
 Traceback (most recent call last):
  File "D:\toolcollection\DISLOCK V2\main.py", line 109, in generate_unclaimed
    await self.page.solve_hcaptcha()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\botright\modules\playwright_mock\page.py", line 334, in solve_mocker
    return await hcaptcha.hCaptcha.solve_hcaptcha(page, rqdata=rqdata)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\botright\modules\hcaptcha.py", line 189, in solve_hcaptcha
    return await hCaptcha.solve_captcha(page, checkbox)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\botright\modules\hcaptcha.py", line 102, in solve_captcha
    image_url = style.split('url("')[1].split('"')[0]
IndexError: list index out of range
```

**To Reproduce**
The Error happen kinda random, i went to the hcaptcha file in `botright/modules/hcaptcha.py` and printed the style variable to see what the content is and got some news regarding the issue:

content of the variable if the captcha got solved with success:
```py
position: absolute; top: 50%; left: 50%; z-index: 5; width: 120px; height: 120px; margin-left: -60px; margin-top: -60px; background: rgba(0, 0, 0, 0) url("https://imgs.hcaptcha.com/IsTLrDDDmlEbx5yG4yXLDBkNnSTQYHZadHCvLN69NQrryCA1NFLbzKr+tckmEbCzEap629sjf6dLltB9hTcRrHd+9MuNl3HaxG4OZkA4y1FchsXaiVNPyb+BwdfGewU8j3I9ofj19Aun2AvvY96bO/EZ6mC05aYPhqiVTkq7GXg/TyS9ll6/vH9HRyOQyfu6/s2S") no-repeat scroll 50% 50% / 120px 120px;
position: absolute; top: 50%; left: 50%; z-index: 5; width: 120px; height: 120px; margin-left: -60px; margin-top: -60px; background: rgba(0, 0, 0, 0) url("https://imgs.hcaptcha.com/DxbqxuaJznkNc4cZYuy2L+f2I5MToE16OxLivxAqLZi00p8H2ZWvdTBzO+m5MAUREmqo4q0yf6caWXm1PhUXR4QBH+V+tZfcM1tj2Sn7HIwbLy/S49bE3Mq9t9TmslmkRyoAFRJgV0ynuK6aojxgT68XnAC8p7/bQL+B+TBLZQ==qKKnj8hbv+rLJJfn") no-repeat scroll 50% 50% / 120px 120px;
position: absolute; top: 50%; left: 50%; z-index: 5; width: 120px; height: 120px; margin-left: -60px; margin-top: -60px; background: rgba(0, 0, 0, 0) url("https://imgs.hcaptcha.com/znYzQ6QPofmqCXUX/EGbiJwiVNEwXqy8WOtOmJc8rtcMeKYaHNytDeQ75usnGCwW8EzVRxPdoECctQzAdM6RNd9T12uQZRBhw1yT/cksWOy1benvCxwGdatkYcF2e3HTATASHeBKMy2B1tvl3T6d7wZwg2iv8AwSI/DvzrI1fw==2QgccADdy+u7huGU") no-repeat scroll 50% 50% / 120px 120px;
position: absolute; top: 50%; left: 50%; z-index: 5; width: 120px; height: 120px; margin-left: -60px; margin-top: -60px; background: rgba(0, 0, 0, 0) url("https://imgs.hcaptcha.com/eEW1fL9QuB7rjmYD1hoToHqVFsoz4ejs1hfLvTByx/8OgGYs1+1QuNp18Mqylon6E2dnHQF3MSgNm73a2XwJ4NFDn1UUUy8oGtCCpE32vMjHwW5KuMJN6SJ1yk+5f8IHGnw4X0CKaE3uzY0b9cHEFRbQt3TB9b76G6CA2DbAhw==aR7VTJCSobgNC4Sf") no-repeat scroll 50% 50% / 120px 120px;
position: absolute; top: 50%; left: 50%; z-index: 5; width: 120px; height: 120px; margin-left: -60px; margin-top: -60px; background: rgba(0, 0, 0, 0) url("https://imgs.hcaptcha.com/NDTe0O4P8SezS6W89fY5l16jHnORW8krpT23x5MuWo1p+seebd2Ry9WFNnspY5rsM8LipA/AN3k+/Xel7KRaB97AuBwTT9LR0xkWHVHBbfYfYYJSB2ULSwQHz972AaDdlVI0YlKPggkRryut0eHsJ0oc8JbNLOTgNLkXl+0Pvp7sVVlWGg==MFJEV3Si/YcUWcqR") no-repeat scroll 50% 50% / 120px 120px;
position: absolute; top: 50%; left: 50%; z-index: 5; width: 120px; height: 120px; margin-left: -60px; margin-top: -60px; background: rgba(0, 0, 0, 0) url("https://imgs.hcaptcha.com/p9gvNAaEyt48qSISLY+mIJ3UAVz8a1XhKDwUtQhBSo+H7yBKNSf1tRGyiZyB4PCBUBtwT0wXIFij3R0dp5oDvIYml0HL/JLuMI8rY3YKevyl5JiwqgsBwuys5nJLGUCOa/Rg9f+1E+OON1MGmV//QI2+o9lbCCf29ujsmukzhiLeVdulPo0=DuM9Aei7uEDwUWMK") no-repeat scroll 50% 50% / 120px 120px;
position: absolute; top: 50%; left: 50%; z-index: 5; width: 120px; height: 120px; margin-left: -60px; margin-top: -60px; background: rgba(0, 0, 0, 0) url("https://imgs.hcaptcha.com/Tm/x3orx3hZtTGr5EILHk3kVUGWkpLsAMKvMiZ7vljzRu6LSYYfdMqMH63kMq66XDaZDRLgbJsvWvnSsWEU2XjYbu8SzlBI8ny7OpHy+kU8pFNiyI3biZaE8tO2eJbBxeZGQk3GyLNc6SWPjZ+f5biLbG/2yfNFAm7xJ904WwFEagS7VE5MVPzjB") no-repeat scroll 50% 50% / 120px 120px;
position: absolute; top: 50%; left: 50%; z-index: 5; width: 120px; height: 120px; margin-left: -60px; margin-top: -60px; background: rgba(0, 0, 0, 0) url("https://imgs.hcaptcha.com/g/WFsO6CwipkByvFFmRt/WRiwTi+SNBj75+1fibGTlFs4V+J+y0QnpFvFM06HSeJfjmSkSpVXb8qb4ZGLS8nUbvQUuzzj128LHHuJSXlF/xnpcryfJi6RTya+9pAY+UiXDHbIJ68oGa/nWL7BK/nYLg1zwVOve0bH/53uiHsgENgDZP2jj4=C88E7AMPrANFdgkG") no-repeat scroll 50% 50% / 120px 120px;
position: absolute; top: 50%; left: 50%; z-index: 5; width: 120px; height: 120px; margin-left: -60px; margin-top: -60px; background: rgba(0, 0, 0, 0) url("https://imgs.hcaptcha.com/pl+z6RhwLbdl+fqzfkCHsMHhF5M4Ix4v7ur9Gu6QIvJzpcL8DVmTSGrou//0Fx5owKJ7DX2zqdXRd/kpF457X8R/xg8ka79Z8vaLktw5WWjzEeHJv+qY5aUJm2K3DXcUtPwp+n5rH6/zA4ObbpMyu1jSzlfs2qalEowWXSJCwL8wUmU+kFBmeoSl") no-repeat scroll 50% 50% / 120px 120px;
```
if the captcha didn't got solved and the keyerror is being raised, the content of the style variable is following:
```py
position: absolute; top: 0px; left: 0px; z-index: 5;
```

**Expected behavior**
Hmm, captcha solving should work as expected i guess

**Screenshots**
Not applicable, error mentioned above

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: https://i.imgur.com/uE8bjf5.png

**Additional context**
404: No other context found.

**Comment by Vinyzu** [comment]
Im rather sure this just happens if the captcha images dont load.
The Captcha pops up then but its just white/grey.
Im just gonna throw an try/except on it for a better/clearer error message.

**Comment by Vinyzu** [comment]
Fixed: https://github.com/Vinyzu/Botright/commit/895d2adab4725b0ee232542899ef0607840d742b
