### ISSUE TITLE
Proxies dont working (browser not start) [BUG] 

### ISSUE THREAD

**Issue by skhrlx** [Vinyzu/Botright#45]
**Describe the bug**
Im trying to use my proxies and is getting some errors, take a look how im trying to start my browser

**Code Sample**
    proxy_settings = {
        'server': 'http://pr.oxylabs.io:7777',
        'username': 'customer-lol',
        'password': 'pass'
    }
    
    botright_client = await botright.Botright(use_undetected_playwright=True, spoof_canvas=True)
    browser = await botright_client.new_browser(proxy=proxy_settings)
    page = await browser.new_page()

**Desktop (please complete the following information):**
 - OS: Win 10

**Console output**
Traceback (most recent call last):
  File "C:\Users\a\source\repos\InstaFucker\InstaFucker.py", line 74, in <module>
    asyncio.run(main())
  File "C:\Users\a\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\a\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\a\source\repos\InstaFucker\InstaFucker.py", line 21, in main
    browser = await botright_client.new_browser(proxy=proxy_settings)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a\AppData\Local\Programs\Python\Python311\Lib\site-packages\botright\botright.py", line 142, in new_browser
    _proxy: ProxyManager = await ProxyManager(self, proxy)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a\AppData\Local\Programs\Python\Python311\Lib\site-packages\async_class.py", line 173, in __await__
    yield from self.create_task(
  File "C:\Users\a\AppData\Local\Programs\Python\Python311\Lib\site-packages\botright\modules\proxy_manager.py", line 47, in __ainit__
    self.proxy = proxy.strip() if proxy else ""
                 ^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'strip'
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x000001851F46E020>
Traceback (most recent call last):
  File "C:\Users\a\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_subprocess.py", line 126, in __del__
  File "C:\Users\a\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_subprocess.py", line 104, in close
  File "C:\Users\a\AppData\Local\Programs\Python\Python311\Lib\asyncio\proactor_events.py", line 109, in close
  File "C:\Users\a\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 761, in call_soon
  File "C:\Users\a\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 519, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function AsyncFileIO.__del__ at 0x000001854E8E94E0>
Traceback (most recent call last):
  File "C:\Users\a\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiomisc\io.py", line 134, in __del__
  File "C:\Users\a\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiomisc\io.py", line 109, in fp
RuntimeError: file is not opened

**Comment by Vinyzu** [comment]
The intended behavior is `browser = await botright_client.new_browser(proxy="user:pass@ip:port", ...)`. But ill add this functionality in the next update to avoid confusion.
