### ISSUE TITLE
[Question]  Botright throws an error in my VM

### ISSUE THREAD

**Issue by simon9428** [Vinyzu/Botright#6]
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\idlelib\run.py", line 578, in runcode
    exec(code, self.locals)
  File "C:\Users\Administrator\Desktop\-_\index.py", line 2, in <module>
    import botright
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\botright\__init__.py", line 3, in <module>
    from .botright import *
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\botright\botright.py", line 6, in <module>
    from .modules.playwright_mock import browser
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\botright\modules\playwright_mock\__init__.py", line 7, in <module>
    from .page import new_page
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\botright\modules\playwright_mock\page.py", line 7, in <module>
    from .. import hcaptcha
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\botright\modules\hcaptcha.py", line 8, in <module>
    from .hcaptcha_challenger import (DIR_CHALLENGE, DIR_MODEL, PATH_OBJECTS_YAML, ArmorCaptcha)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\botright\modules\hcaptcha_challenger\__init__.py", line 6, in <module>
    from .core import ArmorCaptcha
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\botright\modules\hcaptcha_challenger\core.py", line 4, in <module>
    from .solutions import resnet, sk_recognition, yolo
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\botright\modules\hcaptcha_challenger\solutions\sk_recognition.py", line 11, in <module>
    from skimage import feature
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\skimage\_shared\lazy.py", line 62, in __getattr__
    return importlib.import_module(f'{package_name}.{name}')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\skimage\feature\__init__.py", line 4, in <module>
    from ._cascade import Cascade
ImportError: DLL load failed while importing _cascade: 지정된 모듈을 찾을 수 없습니다.

**Comment by Vinyzu** [comment]
https://github.com/Vinyzu/DiscordGenerator/issues/35

Please let me know if this worked!

**Comment by Vinyzu** [comment]
Better Error Description in https://github.com/Vinyzu/Botright/commit/7d6701f434a450845d3386b0ae90d0943d82c0f5
