### ISSUE TITLE
[BUG] Ungoogled Chromium not found

### ISSUE THREAD

**Issue by telmocrp1** [Vinyzu/Botright#81]
Thanks a lot for the work of this repo, it's a goldmine 🚀 

**Describe the bug**
I followed the installation guide but I still have this error:
`[WARNING] Ungoogled Chromium not found. Recommended for Canvas Manipulation. Download at https://ungoogled-software.github.io/ungoogled-chromium-binaries/ `

But ungoogled chromium is installed: 
`type ungoogled-chromium`
`ungoogled-chromium is /usr/bin/ungoogled-chromium`

**Code Sample**
If applicable, add a code sample to replicate the bug.

test code:

```
import asyncio
import botright

async def main():
    botright_client = await botright.Botright()
    # Add the path to your Chromium-based browser here
    browser = await botright_client.new_browser()
    page = await browser.new_page()

    await page.goto("https://google.com")

    await botright_client.close()

if __name__ == "__main__":
    asyncio.run(main())
```

**To Reproduce**
1. Install Botright
2. Install Playwright
3. Install UC chromium

**Expected behavior**
```
Installing models/objects.yaml: 100%|█████████████████████████████████████████████████████████████████████████████████| 3.81k/3.81k [00:00<00:00, 3.71MB/s]
[WARNING] Ungoogled Chromium not found. Recommended for Canvas Manipulation. Download at https://ungoogled-software.github.io/ungoogled-chromium-binaries/ 
Traceback (most recent call last):
  File "/root/test.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/root/test.py", line 5, in main
    botright_client = await botright.Botright()
  File "/usr/local/lib/python3.10/dist-packages/async_class.py", line 173, in __await__
    yield from self.create_task(
  File "/usr/local/lib/python3.10/dist-packages/botright/botright.py", line 90, in __ainit__
    self.browser = self.get_browser_engine()
  File "/usr/local/lib/python3.10/dist-packages/botright/botright.py", line 216, in get_browser_engine
    raise EnvironmentError("No Chromium based browser found")
OSError: No Chromium based browser found
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Comment by giauphan** [comment]
It appears that your issue resembles #36.
