### ISSUE TITLE
[BUG] opencv hcaptcha-challenger

### ISSUE THREAD

**Issue by dlzdrgdr** [Vinyzu/Botright#87]
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/worker/wk-macmini-1-92af8d859120-xmlAq/018e98a5-3e01-8b7b-c8e2-0f6a24718179/wrapper.py", line 9, in <module>
    from u.user import snazzy_script as inner_script
  File "/tmp/worker/wk-macmini-1-92af8d859120-xmlAq/018e98a5-3e01-8b7b-c8e2-0f6a24718179/u/user/snazzy_script.py", line 2, in <module>
    import botright
  File "/tmp/worker/cache/pip/botright==0.5.1/botright/__init__.py", line 1, in <module>
    from .botright import Botright
  File "/tmp/worker/cache/pip/botright==0.5.1/botright/botright.py", line 10, in <module>
    import hcaptcha_challenger as solver
  File "/tmp/worker/cache/pip/hcaptcha-challenger==0.10.1.post2/hcaptcha_challenger/__init__.py", line 13, in <module>
    from hcaptcha_challenger.components.image_classifier import Classifier as BinaryClassifier
  File "/tmp/worker/cache/pip/hcaptcha-challenger==0.10.1.post2/hcaptcha_challenger/components/image_classifier.py", line 12, in <module>
    import cv2
  File "/tmp/worker/cache/pip/opencv-python==4.9.0.80/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/tmp/worker/cache/pip/opencv-python==4.9.0.80/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

I tried to install `opencv-python-headless` but it doesn't work on my docker-linux environment.

Which versions should be used for fix?

Related https://github.com/QIN2DIM/hcaptcha-challenger/issues/593

**Comment by Vinyzu** [comment]
This is an Issue in your cv2 docker-linux environment, not an issue in Botright.
Relevant [StackOverflow](https://stackoverflow.com/a/63377623/16523207)
