### ISSUE TITLE
[BUG] KeyError: 'assets

### ISSUE THREAD

**Issue by FuckingToasters** [Vinyzu/Botright#9]
**Describe the bug**
I assume that this happen because the hcaptcha-challanger github repo got termed so the script can't update itself with new captcha images, if there is a new challanger repo (not found one so far) or a up to date fork, you could replace the urls with that.

**Code Sample**
```py
# main.py
import asyncio
import botright


async def main():
    botright_client = await botright.Botright()
    browser = await botright_client.new_browser()
    page = await browser.new_page()

    tkn = await browser.get_hcaptcha()
    print("tkn: ", tkn)
    page.goto("http://whatsmyuseragent.org/")
    page.screenshot(path="example.png")

    await botright_client.close()

if __name__ == "__main__":
    asyncio.run(main())
```

```py
Traceback (most recent call last):
  File "/home/infinimonster/Documents/Privat/Python/discordphoneverify/new version/plugins/captcha/test.py", line 21, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/infinimonster/Documents/Privat/Python/discordphoneverify/new version/plugins/captcha/test.py", line 9, in main
    botright_client = await botright.Botright()
  File "/home/infinimonster/.local/lib/python3.10/site-packages/async_class.py", line 173, in __await__
    yield from self.create_task(
  File "/home/infinimonster/.local/lib/python3.10/site-packages/botright/botright.py", line 13, in __ainit__
    update_ai()
  File "/home/infinimonster/.local/lib/python3.10/site-packages/botright/modules/hcaptcha_challenger/update.py", line 17, in update_ai
    for asset in release["assets"]:
KeyError: 'assets
```

**To Reproduce**
1. Copy the example code to add to a own script
2. editing a few lines to solve captcha (which is not the issue, the issue lies in the browser initalization)
3.Execute script and  See error

**Expected behavior**
It should execute without any issue, start browser, solve captcha and return the captchatoken

**Screenshots**
I could show screenshots of the error but it's not needed as the error is above.

**Desktop (please complete the following information):**
![2022-12-02_20-39](https://user-images.githubusercontent.com/94435104/205373143-9fd728fc-e8bd-4dee-8288-c6cfa65f8f37.png)

**Additional context**
404: Not found.

**Comment by FuckingToasters** [comment]
noticed the update you made, after installing updated botright with pip install, a new error happens:

OSError: No file or directory found at /home/infinimonster/.local/lib/python3.10/site-packages/botright/modules\recaptcha_model\keras_model.h5

**Comment by Vinyzu** [comment]
> noticed the update you made, after installing updated botright with pip install, a new error happens:
> 
> 
> 
> OSError: No file or directory found at /home/infinimonster/.local/lib/python3.10/site-packages/botright/modules\recaptcha_model\keras_model.h5

Got it, will be fixxed today

**Comment by FuckingToasters** [comment]
> > noticed the update you made, after installing updated botright with pip install, a new error happens:
> > OSError: No file or directory found at /home/infinimonster/.local/lib/python3.10/site-packages/botright/modules\recaptcha_model\keras_model.h5
> 
> Got it, will be fixxed today

thank you <3

**Comment by Vinyzu** [comment]
@FuckingToasters Can you provide me with a tree of all the files/folders in your local botright package? So i can see what files are in there and which arent

**Comment by Vinyzu** [comment]
On linux, you should be able to:
Install `tree` (eg `apt-get install tree`)

And then do
`tree (filepath)`

**Comment by FuckingToasters** [comment]
> On linux, you should be able to: Install `tree` (eg `apt-get install tree`)
> 
> And then do `tree (filepath)`
/home/infinimonster/.local/lib/python3.10/site-packages/botright
├── botright.py
├── __init__.py
├── modules
│   ├── faker.py
│   ├── geetest_helpers.py
│   ├── geetest.py
│   ├── geetest.torchscript
│   ├── hcaptcha_challenger
│   │   └── objects.yaml
│   ├── hcaptcha.py
│   ├── __init__.py
│   ├── names.txt
│   ├── passwords.txt
│   ├── playwright_mock
│   │   ├── browser.py
│   │   ├── element_handle.py
│   │   ├── frame_locator.py
│   │   ├── frame.py
│   │   ├── __init__.py
│   │   ├── js_handle.py
│   │   ├── locator.py
│   │   ├── mouse.py
│   │   ├── page.py
│   │   └── __pycache__
│   │       ├── browser.cpython-310.pyc
│   │       ├── element_handle.cpython-310.pyc
│   │       ├── frame.cpython-310.pyc
│   │       ├── frame_locator.cpython-310.pyc
│   │       ├── __init__.cpython-310.pyc
│   │       ├── js_handle.cpython-310.pyc
│   │       ├── locator.cpython-310.pyc
│   │       ├── mouse.cpython-310.pyc
│   │       └── page.cpython-310.pyc
│   ├── proxy_manager.py
│   ├── __pycache__
│   │   ├── faker.cpython-310.pyc
│   │   ├── geetest.cpython-310.pyc
│   │   ├── geetest_helpers.cpython-310.pyc
│   │   ├── hcaptcha.cpython-310.pyc
│   │   ├── __init__.cpython-310.pyc
│   │   ├── proxy_manager.cpython-310.pyc
│   │   └── recaptcha.cpython-310.pyc
│   ├── recaptcha_model
│   │   ├── __init__.py
│   │   ├── keras_model.h5
│   │   ├── labels.txt
│   │   └── __pycache__
│   │       └── __init__.cpython-310.pyc
│   └── recaptcha.py
└── __pycache__
    ├── botright.cpython-310.pyc
    └── __init__.cpython-310.pyc

**Comment by Vinyzu** [comment]
Mh thats very weird, as you can see, the file exists.
Maybe its because the different type of backslash i use? Go look at the error path again, you'll notice.
Maybe try to change the code so the backsplash is the correct type.

**Comment by Vinyzu** [comment]
Replicated, fixing

**Comment by Vinyzu** [comment]
Fixed, will push update, but hCaptcha Solving isnt working rn anyways cause you only get Dolphin/Panda types and hcap_challenger doesnt support these yet.

**Comment by Vinyzu** [comment]
Fixed: https://github.com/Vinyzu/Botright/commit/7d6701f434a450845d3386b0ae90d0943d82c0f5
(Note: The Pypi Upload takes a bit rn it will come in about 15 Minutes i think)

**Comment by FuckingToasters** [comment]
> Fixed: [7d6701f](https://github.com/Vinyzu/Botright/commit/7d6701f434a450845d3386b0ae90d0943d82c0f5) (Note: The Pypi Upload takes a bit rn it will come in about 15 Minutes i think)

Thank you for the fix, just checked and seem to be working, now we just need to wait until panda and dolphin support is added to hcaptcha-challanger because i only get these 2 images too :)

**Comment by Vinyzu** [comment]
> > Fixed: [7d6701f](https://github.com/Vinyzu/Botright/commit/7d6701f434a450845d3386b0ae90d0943d82c0f5) (Note: The Pypi Upload takes a bit rn it will come in about 15 Minutes i think)
> 
> 
> 
> Thank you for the fix, just checked and seem to be working, now we just need to wait until panda and dolphin support is added to hcaptcha-challanger because i only get these 2 images too :)

No Problem, hope you enjoy botright!
